spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classroom
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/seed

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
